# Generated by Django 4.1.7 on 2023-03-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsule_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='date_precision',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='capsule',
            name='launch_library_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='capsule',
            name='slug',
            field=models.SlugField(default='test'),
        ),
        migrations.AddField(
            model_name='capsule',
            name='static_fire_date_unix',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='capsule',
            name='static_fire_date_utc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
