# Generated by Django 4.1.7 on 2023-03-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsule_app', '0002_capsule_date_precision_capsule_launch_library_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='auto_update',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='capsule',
            name='tbd',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
